changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies and Maintenance
      labels:
        - dependencies
        - github-actions
    - title: Other Changes
      labels:
        - "*"
